<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;

class PermissionsTableSeeder extends Seeder
{
    public function run()
    {

        $permissions = [
            ['name' => 'user.add', 'group_name' => 'User Accounts'],
            ['name' => 'user.view', 'group_name' => 'User Accounts'],
            ['name' => 'user.edit', 'group_name' => 'User Accounts'],
            ['name' => 'user.delete', 'group_name' => 'User Accounts'],
            ['name' => 'user.details', 'group_name' => 'User Accounts'],
            ['name' => 'department.add', 'group_name' => 'Department Management'],
            ['name' => 'department.view', 'group_name' => 'Department Management'],
            ['name' => 'department.edit', 'group_name' => 'Department Management'],
            ['name' => 'department.delete', 'group_name' => 'Department Management'],
            ['name' => 'department.details', 'group_name' => 'Department Management'],
            ['name' => 'designation.add', 'group_name' => 'Designation Management'],
            ['name' => 'designation.view', 'group_name' => 'Designation Management'],
            ['name' => 'designation.edit', 'group_name' => 'Designation Management'],
            ['name' => 'designation.delete', 'group_name' => 'Designation Management'],
            ['name' => 'designation.details', 'group_name' => 'Designation Management'],
            ['name' => 'employee.add', 'group_name' => 'Employee Management'],
            ['name' => 'employee.view', 'group_name' => 'Employee Management'],
            ['name' => 'employee.edit', 'group_name' => 'Employee Management'],
            ['name' => 'employee.delete', 'group_name' => 'Employee Management'],
            ['name' => 'employee.details', 'group_name' => 'Employee Management'],
            ['name' => 'employee.document.add', 'group_name' => 'Employee Management'],
            ['name' => 'employee.document.view', 'group_name' => 'Employee Management'],
            ['name' => 'employee.document.edit', 'group_name' => 'Employee Management'],
            ['name' => 'employee.document.details', 'group_name' => 'Employee Management'],
            ['name' => 'employee.document.delete', 'group_name' => 'Employee Management'],
            ['name' => 'employee.schedule.add', 'group_name' => 'Employee Management'],
            ['name' => 'employee.schedule.view', 'group_name' => 'Employee Management'],
            ['name' => 'employee.schedule.edit', 'group_name' => 'Employee Management'],
            ['name' => 'employee.schedule.details', 'group_name' => 'Employee Management'],
            ['name' => 'employee.schedule.delete', 'group_name' => 'Employee Management'],
            ['name' => 'discount.add', 'group_name' => 'Discount Management'],
            ['name' => 'discount.view', 'group_name' => 'Discount Management'],
            ['name' => 'discount.edit', 'group_name' => 'Discount Management'],
            ['name' => 'discount.delete', 'group_name' => 'Discount Management'],
            ['name' => 'discount.details', 'group_name' => 'Discount Management'],
            ['name' => 'discount.type.add', 'group_name' => 'Discount Management'],
            ['name' => 'discount.type.view', 'group_name' => 'Discount Management'],
            ['name' => 'discount.type.edit', 'group_name' => 'Discount Management'],
            ['name' => 'discount.type.delete', 'group_name' => 'Discount Management'],
            ['name' => 'discount.type.details', 'group_name' => 'Discount Management'],
            ['name' => 'reports.view', 'group_name' => 'Reports'],
            ['name' => 'reports.generate', 'group_name' => 'Reports'],
            ['name' => 'patient.add', 'group_name' => 'Patient Management'],
            ['name' => 'patient.view', 'group_name' => 'Patient Management'],
            ['name' => 'patient.edit', 'group_name' => 'Patient Management'],
            ['name' => 'patient.delete', 'group_name' => 'Patient Management'],
            ['name' => 'patient.details', 'group_name' => 'Patient Management'],
            ['name' => 'fee.add', 'group_name' => 'Fees Management'],
            ['name' => 'fee.view', 'group_name' => 'Fees Management'],
            ['name' => 'fee.edit', 'group_name' => 'Fees Management'],
            ['name' => 'fee.delete', 'group_name' => 'Fees Management'],
            ['name' => 'fee.details', 'group_name' => 'Fees Management'],
            ['name' => 'fee.receipt.add', 'group_name' => 'Fees Management'],
            ['name' => 'fee.receipt.view', 'group_name' => 'Fees Management'],
            ['name' => 'fee.receipt.edit', 'group_name' => 'Fees Management'],
            ['name' => 'fee.receipt.delete', 'group_name' => 'Fees Management'],
            ['name' => 'service.add', 'group_name' => 'Service Management'],
            ['name' => 'service.view', 'group_name' => 'Service Management'],
            ['name' => 'service.edit', 'group_name' => 'Service Management'],
            ['name' => 'service.delete', 'group_name' => 'Service Management'],
            ['name' => 'service.details', 'group_name' => 'Service Management'],
            ['name' => 'service.type.add', 'group_name' => 'Service Management'],
            ['name' => 'service.type.view', 'group_name' => 'Service Management'],
            ['name' => 'service.type.edit', 'group_name' => 'Service Management'],
            ['name' => 'service.type.delete', 'group_name' => 'Service Management'],
            ['name' => 'billing.add', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'billing.view', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'billing.edit', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'billing.delete', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'billing.details', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'receipt.add', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'receipt.view', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'receipt.edit', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'receipt.delete', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'receipt.details', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'sale.invoice.add', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'sale.invoice.view', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'sale.invoice.edit', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'sale.invoice.delete', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'sale.invoice.details', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'sale.return.add', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'sale.return.view', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'sale.return.edit', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'sale.return.delete', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'sale.return.details', 'group_name' => 'Billing/Receipts Mgmt'],
            ['name' => 'pharmacy.company.add', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.company.view', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.company.edit', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.company.delete', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.company.details', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.supplier.add', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.supplier.view', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.supplier.edit', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.supplier.delete', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.supplier.details', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.packing.add', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.packing.view', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.packing.edit', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.packing.delete', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.packing.details', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.product.add', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.product.view', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.product.edit', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.product.delete', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.product.details', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.stock.add', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.stock.view', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.stock.edit', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.stock.delete', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.add', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.view', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.edit', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.delete', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.details', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.search', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.navigate', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.print', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.exportexcel', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.exportpdf', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.cancel', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.store', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.update', 'group_name' => 'Pharmacy Management'],
            ['name' => 'lab.test.add', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.view', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.edit', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.delete', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.details', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.referral.add', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.referral.view', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.referral.edit', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.referral.delete', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.referral.details', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.result.add', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.result.view', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.result.edit', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.result.delete', 'group_name' => 'Laboratory Management'],
            ['name' => 'lab.test.result.details', 'group_name' => 'Laboratory Management'],
            ['name' => 'user.menu', 'group_name' => 'System Setups'],
            ['name' => 'department.menu', 'group_name' => 'System Setups'],
            ['name' => 'designation.menu', 'group_name' => 'System Setups'],
            ['name' => 'employee.menu', 'group_name' => 'System Setups'],
            ['name' => 'discount.menu', 'group_name' => 'System Setups'],
            ['name' => 'patient.menu', 'group_name' => 'System Setups'],
            ['name' => 'fee.menu', 'group_name' => 'System Setups'],
            ['name' => 'service.menu', 'group_name' => 'System Setups'],
            ['name' => 'reciept.menu', 'group_name' => 'System Setups'],
            ['name' => 'general.menu', 'group_name' => 'System Setups'],
            ['name' => 'inventory.menu', 'group_name' => 'System Setups'],
            ['name' => 'billing.menu', 'group_name' => 'System Setups'],
            ['name' => 'test.menu', 'group_name' => 'System Setups'],
            ['name' => 'report.test.menu', 'group_name' => 'System Setups'],
            ['name' => 'permission.meu', 'group_name' => 'System Setups'],
            ['name' => 'reception.menu', 'group_name' => 'System Setups'],
            ['name' => 'pharmacy.purchase.search', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.navigate', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.print', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.exportexcel', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.exportpdf', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.cancel', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.store', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.purchase.update', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.saleinvoice.view', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.saleinvoice.add', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.saleinvoice.edit', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.saleinvoice.delete', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.saleinvoice.preview', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.saleinvoice.print', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.saleinvoice.search', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.saleinvoice.navigate', 'group_name' => 'Pharmacy Management'],
            ['name' => 'pharmacy.saleinvoice.cancel', 'group_name' => 'Pharmacy Management'],
            ['name' => 'sale.invoice.manage', 'group_name' => 'Billing/Receipts Mgmtt'],
            ['name' => 'sale.invoice.search', 'group_name' => 'Billing/Receipts Mgmtt'],
            ['name' => 'fee.receipt.print', 'group_name' => 'Fees Management'],
            ['name' => 'fee.receipt.details', 'group_name' => 'Fees Management']
        ];
        foreach ($permissions as $permission) {
            Permission::firstOrCreate(['name' => $permission['name']], ['group_name' => $permission['group_name']]);
        }
    }
}
