<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchase Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .logo {
            max-width: 100px;
            margin-bottom: 10px;
        }
        h1 {
            font-size: 18px;
            margin: 0;
            padding: 0;
        }
        .info {
            margin-bottom: 15px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 5px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            margin-top: 20px;
            font-size: 10px;
            text-align: center;
        }
        .totals {
            margin-top: 10px;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Life HealthCare Center</h1>
        <p>Sayed Jamaluddin Township Road, Badkhak Square, Arzan Qemat, Kabul</p>
        <p>Contact: 0766 62 62 62</p>
        <p><b>Purchase Report<b></p>
    </div>
    
    <div class="info">
        <p><strong>Date:</strong> {{ date('Y-m-d') }}</p>
        <p><strong>Time:</strong> {{ date('H:i:s') }}</p>
        <p><strong>Generated By:</strong> {{ Auth::user()->name }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>S.No</th>
                <th>Purchase No</th>
                <th>Supplier Name</th>
                <th>Purchase Date</th>
                <th>Net Amount</th>
                <th>Paid Amount</th>
                <th>Due Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($purchases as $key => $purchase)
                <tr>
                    <td style="text-align: center;">{{ $key + 1 }}</td>
                    <td>{{ $purchase->purchase_no }}</td>
                    <td>{{ $purchase->supplier->name ?? 'N/A' }}</td>
                    <td>{{ $purchase->purchase_date }}</td>
                    <td>{{ number_format($purchase->net_amount, 2) }}</td>
                    <td>{{ number_format($purchase->paid_amount, 2) }}</td>
                    <td>{{ number_format($purchase->due_amount, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No records found</td>
                </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <th colspan="4" style="text-align: right;">Total:</th>
                <th>{{ number_format($totalNetAmount, 2) }}</th>
                <th>{{ number_format($totalPaidAmount, 2) }}</th>
                <th>{{ number_format($totalDueAmount, 2) }}</th>
            </tr>
        </tfoot>
    </table>
    
    <div class="footer">
        <p>© {{ date('Y') }} Life HealthCare Center. All rights reserved.</p>
    </div>
</body>
</html>