<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchase Report - Print</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .logo {
            max-width: 80px;
            margin-bottom: 10px;
        }
        h1 {
            font-size: 18px;
            margin: 5px 0;
        }
        h2 {
            font-size: 16px;
            margin: 5px 0;
            color: #555;
        }
        .info {
            margin-bottom: 15px;
            display: flex;
            justify-content: space-between;
        }
        .info-section {
            width: 30%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            margin-top: 20px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            text-align: center;
            font-size: 10px;
        }
        .totals {
            margin-top: 10px;
            text-align: right;
        }
        .totals span {
            font-weight: bold;
            margin-left: 20px;
        }
        @media print {
            body {
                margin: 0;
                padding: 10px;
            }
            .print-button {
                display: none;
            }
        }
        .print-button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 14px;
            margin-bottom: 20px;
        }
        .print-button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <button onclick="window.print()" class="print-button">Print Report</button>
    
    <div class="header">
        <h1>Life HealthCare Center</h1>
        <p>Sayed Jamaluddin Township Road, Badkhak Square, Arzan Qemat, Kabul</p>
        <p>Contact: 0766 62 62 62</p>
        <p><b>Purchase Report<b></p>
        <p>Generated on: {{ date('d-m-Y H:i:s') }}</p>
    </div>
    
    <div class="info">
        <div class="info-section">
            <p><strong>Report Type:</strong> Purchase Report</p>
            <p><strong>Generated By:</strong> {{ Auth::user()->name }}</p>
        </div>
        <div class="info-section">
            <!-- Filters applied -->
            @if(!empty(session('print_filters')))
                <p><strong>Filters Applied:</strong></p>
                <ul style="list-style-type: none; padding-left: 0;">
                    @if(!empty(session('print_filters')['search_purchase_no']))
                        <li>Purchase No: {{ session('print_filters')['search_purchase_no'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['search_purchase_date']))
                        <li>Purchase Date: {{ session('print_filters')['search_purchase_date'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['search_supplier_name']))
                        <li>Supplier: {{ session('print_filters')['search_supplier_name'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchFromDate']) && !empty(session('print_filters')['searchToDate']))
                        <li>Date Range: {{ session('print_filters')['searchFromDate'] }} to {{ session('print_filters')['searchToDate'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchFromId']) && !empty(session('print_filters')['searchToId']))
                        <li>ID Range: {{ session('print_filters')['searchFromId'] }} to {{ session('print_filters')['searchToId'] }}</li>
                    @endif
                </ul>
            @endif
        </div>
        <div class="info-section">
            <p><strong>Total Records:</strong> {{ count($query) }}</p>
            <p><strong>Report ID:</strong> PUR-{{ date('YmdHis') }}</p>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>S.No</th>
                <th>Purchase No</th>
                <th>Supplier Name</th>
                <th>Purchase Date</th>
                <th>Net Amount</th>
                <th>Paid Amount</th>
                <th>Due Amount</th>
            </tr>
        </thead>
        <tbody>
            @forelse($query as $key => $purchase)
                <tr>
                    <td style="text-align: center;">{{ $key + 1 }}</td>
                    <td>{{ $purchase->purchase_no }}</td>
                    <td>{{ $purchase->supplier->name ?? 'N/A' }}</td>
                    <td>{{ $purchase->purchase_date }}</td>
                    <td>{{ number_format($purchase->net_amount, 2) }}</td>
                    <td>{{ number_format($purchase->paid_amount, 2) }}</td>
                    <td>{{ number_format($purchase->due_amount, 2) }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No records found</td>
                </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <th colspan="4" style="text-align: right;">Total:</th>
                <th>{{ number_format($totalNetAmount, 2) }}</th>
                <th>{{ number_format($totalPaidAmount, 2) }}</th>
                <th>{{ number_format($totalDueAmount, 2) }}</th>
            </tr>
        </tfoot>
    </table>
    
    <div class="footer">
        <p>© {{ date('Y') }} Life HealthCare Center. All rights reserved.</p>
        <p>This is a computer-generated document. No signature is required.</p>
    </div>

    <script>
        // Auto-focus to the print button when the page loads
        window.onload = function() {
            document.querySelector('.print-button').focus();
        };
    </script>
</body>
</html>