import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'ps' | 'fa' | 'ar';

interface LandingLanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LandingLanguageContext = createContext<LandingLanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Hero Section
    'hero.badge': 'Trusted by Healthcare Professionals',
    'hero.title': 'ShifaaScript Healthcare Management System',
    'hero.subtitle': '',
    'hero.description': 'Comprehensive prescription management with laboratory tests, medicines, reception management, and role-based access control.',
    'hero.contactUs': 'Contact Us',
    'hero.stats.facilities.number': '50+',
    'hero.stats.facilities.label': 'Active Users',
    'hero.stats.prescriptions.number': '1,200+',
    'hero.stats.prescriptions.label': 'Prescriptions/Month',
    'hero.stats.uptime.number': '99%',
    'hero.stats.uptime.label': 'System Reliability',
    'hero.stats.support.number': '24/7',
    'hero.stats.support.label': 'Support Available',

    // Features Section
    'features.title': 'Core Features',
    'features.subtitle': 'Everything you need in one integrated platform',
    'features.prescription.title': 'Smart Prescriptions',
    'features.prescription.desc': 'Fast prescription creation with auto-calculation and print output',
    'features.medicine.title': 'Medicine Database',
    'features.medicine.desc': 'Complete inventory tracking with automated stock alerts',
    'features.lab.title': 'Lab Management',
    'features.lab.desc': 'Digital test ordering, tracking, and result management',
    'features.patient.title': 'Patient Records',
    'features.patient.desc': 'Auto-generated IDs with complete medical history',
    'features.rbac.title': 'Access Control',
    'features.rbac.desc': 'Multi-tenant system with strict data isolation',
    'features.appointment.title': 'Appointments',
    'features.appointment.desc': 'Calendar integration with automated reminders',

    // Excellence Section
    'excellence.title': 'Designed for Healthcare Excellence',
    'excellence.subtitle': 'ShifaaScript combines modern technology with healthcare expertise to deliver a solution that truly understands your needs.',
    'excellence.multiLang.title': 'Multi-Language Support',
    'excellence.multiLang.desc': 'Available in English, Pashto, Dari, and Arabic with full RTL support',
    'excellence.print.title': 'Professional Print Layouts',
    'excellence.print.desc': 'Beautiful prescription and report templates with QR codes for verification',
    'excellence.calendar.title': 'Calendar Flexibility',
    'excellence.calendar.desc': 'Support for both Gregorian and Hijri Shamsi (Solar) calendars',
    'excellence.theme.title': 'Dark/Light Theme',
    'excellence.theme.desc': 'Comfortable viewing experience with automatic theme switching',
    'excellence.analytics.title': 'Real-Time Analytics',
    'excellence.analytics.desc': 'Comprehensive dashboards with charts, statistics, and insights',
    'excellence.badge1': 'Fast Workflow',
    'excellence.badge2': 'Print Ready',
    'excellence.badge3': 'QR Verification',
    'excellence.badge4': 'Multi-Language',
    'excellence.badge5': 'Secure Access',
    'excellence.badge6': 'Analytics',

    // Capabilities Section
    'capabilities.title': 'Powerful Features for Modern Healthcare',
    'capabilities.subtitle': 'Built with the latest technology to provide you with the best healthcare management experience',
    'capabilities.multi.title': 'Multi-Tenant Architecture',
    'capabilities.multi.desc': 'Complete data isolation between hospitals with role-based access control',
    'capabilities.theme.title': 'Dark/Light Theme',
    'capabilities.theme.desc': 'Professional themes with RTL support for Arabic, Pashto, and Dari languages',
    'capabilities.print.title': 'Print-Ready Prescriptions',
    'capabilities.print.desc': 'Professional prescription layouts with QR codes and hospital branding',
    'capabilities.reports.title': 'Advanced Analytics',
    'capabilities.reports.desc': 'Comprehensive reports and charts for better decision making',

    // CTA Section
    'cta.title': 'Ready to Transform Your Healthcare Practice?',
    'cta.subtitle': 'Join healthcare professionals who trust ShifaaScript for their daily operations',
    'cta.getStarted': 'Get Started Today',
    'cta.contact': 'Contact Us',

    // Developers Section
    'developers.title': 'Meet Our Development Team',
    'developers.subtitle': 'Expert developers dedicated to building world-class healthcare solutions',
    'developers.dev1.name': 'Sadiq Aminzai',
    'developers.dev1.role': 'Full Stack Developer',
    'developers.dev2.name': 'Raz Mohammad Sahar',
    'developers.dev2.role': 'Full Stack Developer',
    'developers.dev3.name': 'Mohammad Bilal Niazi',
    'developers.dev3.role': 'Backend Developer',
    'developers.dev1.phone': '0093789681010',
    'developers.dev1.email': 'sadiq.aminzai2014@gmail.com',
    'developers.dev2.phone': '0093701021319',
    'developers.dev2.email': 'raz.sahar2@gmail.com',
    'developers.dev3.phone': '0093789795964',
    'developers.dev3.email': 'mohammadbilalniazi2016@gmail.com',

    // Contact Section
    'contact.title': 'Get In Touch',
    'contact.subtitle': 'Have questions? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    'contact.info': 'Contact Information',
    'contact.address': 'Address',
    'contact.addressKabul': 'Kabul:',
    'contact.addressKabulText': 'Four floor, Dawoodzai Business Center, Kabul, Afghanistan',
    'contact.addressKhost': 'Khost:',
    'contact.addressKhostText': 'Salam Plaza Tower, 2nd Floor, Khost, Afghanistan',
    'contact.phone': 'Phone',
    'contact.phone1': '+93 789 681 010',
    'contact.phone2': '+93 701 021 319',
    'contact.email': 'Email',
    'contact.email1': 'sadiq.aminzai2014@gmail.com',
    'contact.email2': 'raz.sahar2@gmail.com',
    'contact.email3': 'mohammadbilalniazi2016@gmail.com',
    'contact.hours': 'Working Hours',
    'contact.hoursText': 'Saturday - Thursday: 8:00 AM - 5:00 PM\nFriday: Closed',
    'contact.viewMap': 'View on Google Maps',
    'contact.form.title': 'Send Us a Message',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phoneLabel': 'Phone Number',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.namePlaceholder': 'Ayaan',
    'contact.form.emailPlaceholder': 'ayaan@email.com',
    'contact.form.phonePlaceholder': '07XXXXXXXX',
    'contact.form.subjectPlaceholder': 'Inquiry about the system',
    'contact.form.messagePlaceholder': 'I would like to know more about ShifaaScript features...',

    // Footer
    'footer.tagline': 'Healthcare Management System',
    'footer.description': 'Empowering healthcare professionals with modern, efficient, and user-friendly management solutions.',
    'footer.phone1': '+93 789 681 010',
    'footer.phone2': '+93 701 021 319',
    'footer.products': 'Other Products',
    'footer.product1': 'Hospital MIS',
    'footer.product2': 'School ERP',
    'footer.product3': 'POS for Supermarket',
    'footer.product4': 'Slaughterhouse System',
    'footer.product5': 'Business Profile Website',
    'footer.support': 'Support',
    'footer.contactUs': 'Contact Us',
    'footer.helpCenter': 'Help Center',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.copyright': '© 2026 ShifaaScript. All rights reserved. Enterprise healthcare management solution.',

    // Validation
    'validation.nameMin': 'Full name must be at least 3 characters',
    'validation.emailInvalid': 'Please enter a valid email address',
    'validation.phoneInvalid': 'Phone number must be exactly 10 digits',
    'validation.subjectLength': 'Subject must be between 5-20 characters',
    'validation.messageLength': 'Message must be between 12-96 characters',
    'validation.fixErrors': 'Please fix validation errors',
    'validation.success': 'Message sent successfully! We\'ll get back to you soon.',
  },

  ps: {
    // Hero Section
    'hero.badge': 'د روغتیا متخصصینو لخوا با شوی',
    'hero.title': 'شفاسکرپټ د روغتیا مدیریت سیسټم',
    'hero.subtitle': '',
    'hero.description': 'د نسخو جامع مدیریت د لابراتواري ازموینو، درملو، د استقبال مدیریت او د رول پر بنسټ د لاسرسي کنترول سره',
    'hero.contactUs': 'موږ سره اړیکه ونیسئ',
    'hero.stats.facilities.number': '50+',
    'hero.stats.facilities.label': 'فعال کاروونکي',
    'hero.stats.prescriptions.number': '1,200+',
    'hero.stats.prescriptions.label': 'مياشتينی نسخې',
    'hero.stats.uptime.number': '99%',
    'hero.stats.uptime.label': 'د سیسټم موثقیت',
    'hero.stats.support.number': '24/7',
    'hero.stats.support.label': 'ملاتړ شتون',

    // Features Section
    'features.title': 'اصلي ځانګړتیاوې',
    'features.subtitle': 'په یوه مربوط پلیټ فارم کې هر څه چې تاسو ورته اړتیا لرئ',
    'features.prescription.title': 'هوښیار نسخې',
    'features.prescription.desc': 'د خودکار محاسبې او چاپ محصول سره ګړندۍ نسخې جوړول',
    'features.medicine.title': 'د درملو ډیټابیس',
    'features.medicine.desc': 'د خودکار سټاک خبرتیاو سره بشپړ انوینټري تعقیب',
    'features.lab.title': 'د لابراتوار مدیریت',
    'features.lab.desc': 'ډیجیټل ټیسټ امر، تعقیب او د پایلو مدیریت',
    'features.patient.title': 'د ناروغ ریکارډونه',
    'features.patient.desc': 'د بشپړ طبی تاریخ سره خودکار تولید شوي ID',
    'features.rbac.title': 'د لاسرسي کنترول',
    'features.rbac.desc': 'د سخت ډیټا جلا کولو سره څو کرایه کونکي سیسټم',
    'features.appointment.title': 'ملاقاتونه',
    'features.appointment.desc': 'د خودکار یادونو سره د کیلنډر ادغام',

    // Excellence Section
    'excellence.title': 'د روغتیا غوره والي لپاره ډیزاین شوی',
    'excellence.subtitle': 'شفاسکرپټ د روغتیا تخصص سره عصري ټیکنالوژي یوځای کوي ترڅو یو داسې حل چمتو کړي چې واقعیا ستاسو اړتیاوې پوهیږي.',
    'excellence.multiLang.title': 'څو ژبې ملاتړ',
    'excellence.multiLang.desc': 'په انګلیسي، پښتو، دري او عربي کې د بشپړ RTL ملاتړ سره شتون لري',
    'excellence.print.title': 'مسلکي چاپ طرح',
    'excellence.print.desc': 'د تصدیق لپاره د QR کوډونو سره ښکلي نسخې او راپور ټیمپلیټونه',
    'excellence.calendar.title': 'د کیلنډر انعطاف',
    'excellence.calendar.desc': 'د ګریګورین او هجري شمسي (لمریز) کیلنډرونو دواړو لپاره ملاتړ',
    'excellence.theme.title': 'تیاره/روښانه تیما',
    'excellence.theme.desc': 'د خودکار تیما بدلولو سره آرامه لید تجربه',
    'excellence.analytics.title': 'د ریښتیني وخت تحلیل',
    'excellence.analytics.desc': 'د چارټونو، احصایو او بصیرتونو سره جامع ډشبورډونه',
    'excellence.badge1': 'ګړندی کاري بهیر',
    'excellence.badge2': 'چاپ چمتو',
    'excellence.badge3': 'QR تصدیق',
    'excellence.badge4': 'څو ژبې',
    'excellence.badge5': 'خوندي لاسرسی',
    'excellence.badge6': 'تحلیل',

    // Capabilities Section
    'capabilities.title': 'د عصري روغتیا لپاره پیاوړې ځانګړتیاوې',
    'capabilities.subtitle': 'د تازه ټیکنالوژۍ سره جوړ شوی ترڅو تاسو ته د روغتیا مدیریت غوره تجربه چمتو کړي',
    'capabilities.multi.title': 'څو کرایه کونکي جوړښت',
    'capabilities.multi.desc': 'د روغتونونو ترمنځ د ډیټا بشپړه جلا کول د رول پر بنسټ د لاسرسي کنټرول سره',
    'capabilities.theme.title': 'تیاره/روښانه تیما',
    'capabilities.theme.desc': 'د عربي، پښتو او دري ژبو لپاره د RTL ملاتړ سره مسلکي تیماوې',
    'capabilities.print.title': 'چاپ چمتو نسخې',
    'capabilities.print.desc': 'د QR کوډونو او روغتون برانډینګ سره مسلکي نسخې ترتیب',
    'capabilities.reports.title': 'پرمختللی تحلیل',
    'capabilities.reports.desc': 'د غوره پریکړې کولو لپاره جامع راپورونه او چارټونه',

    // CTA
    'cta.title': 'ایا تاسو چمتو یاست چې خپل روغتیا خدمات بدل کړئ؟',
    'cta.subtitle': 'د روغتیا متخصصینو سره یوځای شئ چې د خپلو ورځنیو عملیاتو لپاره په شفاسکرپټ باور لري',
    'cta.getStarted': 'نن پیل کړئ',
    'cta.contact': 'موږ سره اړیکه ونیسئ',

    // Developers
    'developers.title': 'Meet Our Development Team',
    'developers.subtitle': 'Expert developers dedicated to building world-class healthcare solutions',
    'developers.dev1.name': 'Sadiq Aminzai',
    'developers.dev1.role': 'Full Stack Developer',
    'developers.dev2.name': 'Raz Mohammad Sahar',
    'developers.dev2.role': 'Full Stack Developer',
    'developers.dev3.name': 'Mohammad Bilal Niazi',
    'developers.dev3.role': 'Backend Developer',
    'developers.dev1.phone': '0093789681010',
    'developers.dev1.email': 'sadiq.aminzai2014@gmail.com',
    'developers.dev2.phone': '0093701021319',
    'developers.dev2.email': 'raz.sahar2@gmail.com',
    'developers.dev3.phone': '0093789795964',
    'developers.dev3.email': 'mohammadbilalniazi2016@gmail.com',

    // Contact
    'contact.title': 'اړیکه ونیسئ',
    'contact.subtitle': 'پوښتنې لرئ؟ موږ به خوښ شو چې ستاسو څخه واورو. موږ ته پیغام راولیږئ او موږ به ژر تر ژره ځواب درکړو.',
    'contact.info': 'د اړیکې معلومات',
    'contact.address': 'پته',
    'contact.addressKabul': 'کابل:',
    'contact.addressKabulText': 'د داودزی تجارتي مرکز، څلورم پوړ، کابل، افغانستان',
    'contact.addressKhost': 'خوست:',
    'contact.addressKhostText': 'برج سلام دوهم پوړ، خوست افغانستان',
    'contact.phone': 'تلیفون',
    'contact.phone1': '۰۰۹۳۷۸۹۶۸۱۰۱۰',
    'contact.phone2': '۰۰۹۳۷۰۱۰۲۱۳۱۹',
    'contact.email': 'ایمیل',
    'contact.email1': 'sadiq.aminzai2014@gmail.com',
    'contact.email2': 'raz.sahar2@gmail.com',
    'contact.email3': 'mohammadbilalniazi2016@gmail.com',
    'contact.hours': 'د کار ساعتونه',
    'contact.hoursText': 'شنبه - پنجشنبه: 8:00 صبح - 5:00 ماښام\nجمعه: تړل شوی',
    'contact.viewMap': 'په ګوګل نقشو کې وګورئ',
    'contact.form.title': 'موږ ته یو پیغام راولیږئ',
    'contact.form.name': 'بشپړ نوم',
    'contact.form.email': 'د برېښنالیک پته',
    'contact.form.phoneLabel': 'د تلیفون شمېره',
    'contact.form.subject': 'موضوع',
    'contact.form.message': 'پیغام',
    'contact.form.send': 'پیغام ولیږئ',
    'contact.form.sending': 'لیږل کیږي...',
    'contact.form.namePlaceholder': 'ایان',
    'contact.form.emailPlaceholder': 'ayaan@email.com',
    'contact.form.phonePlaceholder': '٠٧XXXXXXXX',
    'contact.form.subjectPlaceholder': 'د سیسټم په اړه پوښتنه',
    'contact.form.messagePlaceholder': 'زه غواړم د شفاسکرپټ ځانګړتیاوو په اړه نور معلومات ترلاسه کړم...',

    // Footer
    'footer.tagline': 'د روغتیا مدیریت سیسټم',
    'footer.description': 'د عصري، اغیزمن او کاروونکي دوستانه مدیریت حلونو سره د روغتیا متخصصینو پیاوړتیا.',
    'footer.phone1': '۰۰۹۳۷۸۹۶۸۱۰۱۰',
    'footer.phone2': '۰۰۹۳۷۰۱۰۲۱۳۱۹',
    'footer.products': 'نور محصولات',
    'footer.product1': 'د روغتون MIS',
    'footer.product2': 'د ښوونځي ERP',
    'footer.product3': 'د سوپرمارکیټ لپاره POS',
    'footer.product4': 'د څارويو حلالو اړوند سيستم',
    'footer.product5': 'د سوداګرۍ پروفایل ویب پاڼه',
    'footer.support': 'ملاتړ',
    'footer.contactUs': 'موږ سره اړیکه ونیسئ',
    'footer.helpCenter': 'د مرستې مرکز',
    'footer.privacy': 'د محرمیت پالیسي',
    'footer.terms': 'د خدمت شرایط',
    'footer.copyright': '© 2026 شفاسکرپټ. ټول حقوق خوندي دي. د تشبث روغتیایی مدیریت حل.',

    // Validation
    'validation.nameMin': 'بشپړ نوم باید لږ تر لږه 3 حروف ولري',
    'validation.emailInvalid': 'مهرباني وکړئ یو معتبر ایمیل پته دننه کړئ',
    'validation.phoneInvalid': 'د تلیفون شمېره باید دقیقاً 10 عدده وي',
    'validation.subjectLength': 'موضوع باید د 5-20 حروفو ترمنځ وي',
    'validation.messageLength': 'پیغام باید د 12-96 حروفو ترمنځ وي',
    'validation.fixErrors': 'مهرباني وکړئ د تایید تېروتنې سم کړئ',
    'validation.success': 'پیغام په بریالیتوب سره ولیږل شو! موږ به ژر تر ژره تاسو ته بیرته راشو.',
  },

  fa: {
    // Hero Section
    'hero.badge': 'توافق با متخصصان صحی',
    'hero.title': 'شفاسکریپت سیستم مدیریت مراقبت های صحی',
    'hero.subtitle': '',
    'hero.description': 'مدیریت جامع نسخه با آزمایش های آزمایشگاهی، دارو، مدیریت پذیرش و کنترل دسترسی مبتنی بر نقش',
    'hero.contactUs': 'با ما تماس بگیرید',
    'hero.stats.facilities.number': '50+',
    'hero.stats.facilities.label': 'کاربران فعال',
    'hero.stats.prescriptions.number': '1,200+',
    'hero.stats.prescriptions.label': 'نسخه های ماهانه',
    'hero.stats.uptime.number': '99%',
    'hero.stats.uptime.label': 'قابلیت اطمینان سیستم',
    'hero.stats.support.number': '24/7',
    'hero.stats.support.label': 'پشتیبانی در دسترس',

    // Features
    'features.title': 'ویژگی های اصلی',
    'features.subtitle': 'هر چیزی که نیاز دارید در یک پلتفرم',
    'features.prescription.title': 'نسخه های هوشمند',
    'features.prescription.desc': 'ایجاد سریع نسخه با محاسبه خودکار و چاپ',
    'features.medicine.title': 'پایگاه داده دارو',
    'features.medicine.desc': 'ردیابی کامل موجودی با هشدارهای خودکار',
    'features.lab.title': 'مدیریت آزمایشگاه',
    'features.lab.desc': 'سفارش، ردیابی و نتایج دیجیتال آزمایش',
    'features.patient.title': 'سوابق بیمار',
    'features.patient.desc': 'شناسه خودکار با تاریخچه پزشکی کامل',
    'features.rbac.title': 'کنترل دسترسی',
    'features.rbac.desc': 'سیستم چند مستاجر با جداسازی داده ها',
    'features.appointment.title': 'قرار ملاقات',
    'features.appointment.desc': 'ادغام تقویم با یادآوری خودکار',

    // Excellence
    'excellence.title': 'طراحی برای ممتازیت در مراقبت های صحی',
    'excellence.subtitle': 'شفاسکریپت ترکیب فناوری مدرن و تخصص در مراقبت های صحی را برای ارائه یک راه حل است که نیازهای شما را واقعاً درک می کند.',
    'excellence.multiLang.title': 'پشتیبانی از چند زبان',
    'excellence.multiLang.desc': 'در دسترس در انگلیسی، پشتو، دری و عربی با پشتیبانی کامل RTL',
    'excellence.print.title': 'طرح بندی چاپی حرفه ای',
    'excellence.print.desc': 'قالب های نسخه و گزارش حرفه ای با کدهای QR برای تأیید',
    'excellence.calendar.title': 'پیچیدگی تقویم',
    'excellence.calendar.desc': 'پشتیبانی از تقویم گریگوریان و هجری شمسی (سولار)',
    'excellence.theme.title': 'تم تاریک/روشن',
    'excellence.theme.desc': 'تجربه مشاهده مهربان با تغییر خودکار تم',
    'excellence.analytics.title': 'تحلیلات زمان واقعی',
    'excellence.analytics.desc': 'داشبوردهای جامع با چارت ها، آمارها و نظریات',
    'excellence.badge1': 'گردش کار سریع',
    'excellence.badge2': 'چاپ آماده',
    'excellence.badge3': 'تأیید QR',
    'excellence.badge4': 'چند زبانه',
    'excellence.badge5': 'دسترسی امن',
    'excellence.badge6': 'تحلیل',

    // Capabilities
    'capabilities.title': 'ویژگی های قدرتمند برای مراقبت های صحی مدرن',
    'capabilities.subtitle': 'با جدیدترین فناوری ساخته شده تا بهترین تجربه مدیریت مراقبت های صحی را به شما ارائه دهد',
    'capabilities.multi.title': 'معماری چند مستاجر',
    'capabilities.multi.desc': 'جداسازی کامل داده ها بین شفاخانه ها با کنترل دسترسی مبتنی بر نقش',
    'capabilities.theme.title': 'تم تاریک/روشن',
    'capabilities.theme.desc': 'تم های حرفه ای با پشتیبانی RTL برای زبان های عربی، پشتو و دری',
    'capabilities.print.title': 'نسخه های آماده چاپ',
    'capabilities.print.desc': 'طرح بندی نسخه حرفه ای با کدهای QR و برندسازی شفاخانه',
    'capabilities.reports.title': 'تجزیه و تحلیل پیشرفته',
    'capabilities.reports.desc': 'گزارش ها و نمودارهای جامع برای تصمیم گیری بهتر',

    // CTA
    'cta.title': 'آیا آماده تحول خدمات صحی خود هستید؟',
    'cta.subtitle': 'به متخصصان صحی بپیوندید که برای عملیات روزانه خود به شفاسکریپت اعتماد دارند',
    'cta.getStarted': 'امروز شروع کنید',
    'cta.contact': 'با ما تماس بگیرید',

    // Developers
    'developers.title': 'Meet Our Development Team',
    'developers.subtitle': 'Expert developers dedicated to building world-class healthcare solutions',
    'developers.dev1.name': 'Sadiq Aminzai',
    'developers.dev1.role': 'Full Stack Developer',
    'developers.dev2.name': 'Raz Mohammad Sahar',
    'developers.dev2.role': 'Full Stack Developer',
    'developers.dev3.name': 'Mohammad Bilal Niazi',
    'developers.dev3.role': 'Backend Developer',
    'developers.dev1.phone': '0093789681010',
    'developers.dev1.email': 'sadiq.aminzai2014@gmail.com',
    'developers.dev2.phone': '0093701021319',
    'developers.dev2.email': 'raz.sahar2@gmail.com',
    'developers.dev3.phone': '0093789795964',
    'developers.dev3.email': 'mohammadbilalniazi2016@gmail.com',

    // Contact
    'contact.title': 'با ما در تماس باشید',
    'contact.subtitle': 'سؤالی دارید؟ ما دوست داریم از شما بشنویم. برای ما پیام بفرستید و ما در اسرع وقت پاسخ خواهیم داد.',
    'contact.info': 'اطلاعات تماس',
    'contact.address': 'آدرس',
    'contact.addressKabul': 'کابل:',
    'contact.addressKabulText': 'مرکز تجارتی داوودزای، طبقه چهارم، کابل، افغانستان',
    'contact.addressKhost': 'خوست:',
    'contact.addressKhostText': 'برج سلام پلازا، طبقه دوم، شهر خوست، افغانستان',
    'contact.phone': 'تلفن',
    'contact.phone1': '۰۰۹۳۷۸۹۶۸۱۰۱۰',
    'contact.phone2': '۰۰۹۳۷۰۱۰۲۱۳۱۹',
    'contact.email': 'ایمیل',
    'contact.email1': 'sadiq.aminzai2014@gmail.com',
    'contact.email2': 'raz.sahar2@gmail.com',
    'contact.email3': 'mohammadbilalniazi2016@gmail.com',
    'contact.hours': 'ساعات کاری',
    'contact.hoursText': 'شنبه - پنجشنبه: 8:00 صبح - 5:00 بعدازظهر\nجمعه: بسته',
    'contact.viewMap': 'در نقشه گوگل مشاهده کنید',
    'contact.form.title': 'برای ما پیام بفرستید',
    'contact.form.name': 'نام کامل',
    'contact.form.email': 'آدرس ایمیل',
    'contact.form.phoneLabel': 'شماره تلفن',
    'contact.form.subject': 'موضوع',
    'contact.form.message': 'پیام',
    'contact.form.send': 'ارسال پیام',
    'contact.form.sending': 'در حال ارسال...',
    'contact.form.namePlaceholder': 'ایان',
    'contact.form.emailPlaceholder': 'ayaan@email.com',
    'contact.form.phonePlaceholder': 'XXXXXXXX٠٧',
    'contact.form.subjectPlaceholder': 'استعلام در مورد سیستم',
    'contact.form.messagePlaceholder': 'من می خواهم در مورد ویژگی های شفاسکریپت بیشتر بدانم...',

    // Footer
    'footer.tagline': 'سیستم مدیریت مراقبت های صحی',
    'footer.description': 'توانمندسازی متخصصان صحی با راه حل های مدیریتی مدرن، کارآمد و کاربر پسند.',
    'footer.phone1': '۰۰۹۳۷۸۹۶۸۱۰۱۰',
    'footer.phone2': '۰۰۹۳۷۰۱۰۲۱۳۱۹',
    'footer.products': 'محصولات دیگر',
    'footer.product1': 'سیستم اطلاعات شفاخانه',
    'footer.product2': 'سیستم مدیریت مدرسه',
    'footer.product3': 'سیستم فروش برای سوپرمارکت',
    'footer.product4': 'سیستم سلاخ خانه',
    'footer.product5': 'وب سایت پروفایل تجاری',
    'footer.support': 'پشتیبانی',
    'footer.contactUs': 'با ما تماس بگیرید',
    'footer.helpCenter': 'مرکز کمک',
    'footer.privacy': 'سیاست حفظ حریم خصوصی',
    'footer.terms': 'شرایط خدمات',
    'footer.copyright': '© 2026 شفاسکریپت. کلیه حقوق محفوظ است. راه حل مدیریت مراقبت های صحی سازمانی.',

    // Validation
    'validation.nameMin': 'نام کامل باید حداقل 3 حرف باشد',
    'validation.emailInvalid': 'لطفاً یک آدرس ایمیل معتبر وارد کنید',
    'validation.phoneInvalid': 'شماره تلفن باید دقیقاً 10 رقم باشد',
    'validation.subjectLength': 'موضوع باید بین 5-20 حرف باشد',
    'validation.messageLength': 'پیام باید بین 12-96 حرف باشد',
    'validation.fixErrors': 'لطفاً خطاهای اعتبارسنجی را برطرف کنید',
    'validation.success': 'پیام با موفقیت ارسال شد! ما به زودی به شما پاسخ خواهیم داد.',
  },

  ar: {
    // Hero Section
    'hero.badge': 'موثوق به محترفي الرعاية الصحية',
    'hero.title': 'شفاء سكريبت نظام إدارة الرعاية الصحية',
    'hero.subtitle': '',
    'hero.description': 'إدارة شاملة للوصفات الطبية مع الفحوصات المختبرية، الأدوية، إدارة الاستقبال، والتحكم في الوصول على أساس الأدوار',
    'hero.contactUs': 'اتصل بنا',
    'hero.stats.facilities.number': '50+',
    'hero.stats.facilities.label': 'مستخدمون نشطون',
    'hero.stats.prescriptions.number': '1,200+',
    'hero.stats.prescriptions.label': 'وصفات/شهر',
    'hero.stats.uptime.number': '99%',
    'hero.stats.uptime.label': 'موثوقية النظام',
    'hero.stats.support.number': '24/7',
    'hero.stats.support.label': 'دعم متاح',

    // Features
    'features.title': 'الميزات الأساسية',
    'features.subtitle': 'كل ما تحتاجه في منصة واحدة',
    'features.prescription.title': 'وصفات ذكية',
    'features.prescription.desc': 'إنشاء سريع مع حساب تلقائي وطباعة',
    'features.medicine.title': 'قاعدة بيانات الأدوية',
    'features.medicine.desc': 'تتبع كامل للمخزون مع تنبيهات تلقائية',
    'features.lab.title': 'إدارة المختبر',
    'features.lab.desc': 'طلب وتتبع ونتائج رقمية للفحوصات',
    'features.patient.title': 'سجلات المرضى',
    'features.patient.desc': 'معرفات تلقائية مع تاريخ طبي كامل',
    'features.rbac.title': 'تحكم في الوصول',
    'features.rbac.desc': 'نظام متعدد المستأجرين مع عزل البيانات',
    'features.appointment.title': 'المواعيد',
    'features.appointment.desc': 'تكامل التقويم مع تذكيرات تلقائية',

    // Excellence
    'excellence.title': 'تصميم لتميز الرعاية الصحية',
    'excellence.subtitle': 'شفاء سكريبت يجمع بين التكنولوجيا الحديثة والخبرة في الرعاية الصحية لتقديم حل يفهم حقًا احتياجاتك.',
    'excellence.multiLang.title': 'دعم متعدد اللغات',
    'excellence.multiLang.desc': 'متاح بالإنجليزية والبشتو والدرية والعربية مع دعم RTL كامل',
    'excellence.print.title': 'تخطيطات طباعة حرفية',
    'excellence.print.desc': 'قوالب وصفات وتقارير حرفية مع رموز QR للتحقق',
    'excellence.calendar.title': 'مرونة التقويم',
    'excellence.calendar.desc': 'دعم للتقويم الميلادي والتقويم الهجري الشمسي (السولاري)',
    'excellence.theme.title': 'سمة داكنة/فاتحة',
    'excellence.theme.desc': 'تجربة مشاهدة مريحة مع تغيير تلقائي للسمة',
    'excellence.analytics.title': 'تحليلات في الوقت الحقيقي',
    'excellence.analytics.desc': 'لوحات معلوماتية شاملة مع الرسوم البيانية والإحصائيات والرؤى',
    'excellence.badge1': 'عملية سريعة',
    'excellence.badge2': 'جاهز للطباعة',
    'excellence.badge3': 'تحقق QR',
    'excellence.badge4': 'متعدد اللغات',
    'excellence.badge5': 'وصول آمن',
    'excellence.badge6': 'تحليلات',

    // Capabilities
    'capabilities.title': 'ميزات قوية للرعاية الصحية الحديثة',
    'capabilities.subtitle': 'مبني بأحدث التقنيات لتزويدك بأفضل تجربة إدارة رعاية صحية',
    'capabilities.multi.title': 'بنية متعددة المستأجرين',
    'capabilities.multi.desc': 'عزل كامل للبيانات بين المستشفيات مع التحكم في الوصول على أساس الدور',
    'capabilities.theme.title': 'سمة داكنة/فاتحة',
    'capabilities.theme.desc': 'سمات احترافية مع دعم RTL للغات العربية والبشتو والدرية',
    'capabilities.print.title': 'وصفات جاهزة للطباعة',
    'capabilities.print.desc': 'تخطيطات وصفات احترافية مع رموز QR وعلامة تجارية للمستشفى',
    'capabilities.reports.title': 'تحليلات متقدمة',
    'capabilities.reports.desc': 'تقارير ومخططات شاملة لاتخاذ قرارات أفضل',

    // CTA
    'cta.title': 'هل أنت مستعد لتحويل ممارستك الصحية؟',
    'cta.subtitle': 'انضم إلى المهنيين الحيين الين يثقون في شفاء سكريبت لعملياتهم اليومية',
    'cta.getStarted': 'ابدأ اليوم',
    'cta.contact': 'اتصل بنا',

    // Developers
    'developers.title': 'Meet Our Development Team',
    'developers.subtitle': 'Expert developers dedicated to building world-class healthcare solutions',
    'developers.dev1.name': 'Sadiq Aminzai',
    'developers.dev1.role': 'Full Stack Developer',
    'developers.dev2.name': 'Raz Mohammad Sahar',
    'developers.dev2.role': 'Full Stack Developer',
    'developers.dev3.name': 'Mohammad Bilal Niazi',
    'developers.dev3.role': 'Backend Developer',
    'developers.dev1.phone': '0093789681010',
    'developers.dev1.email': 'sadiq.aminzai2014@gmail.com',
    'developers.dev2.phone': '0093701021319',
    'developers.dev2.email': 'raz.sahar2@gmail.com',
    'developers.dev3.phone': '0093789795964',
    'developers.dev3.email': 'mohammadbilalniazi2016@gmail.com',

    // Contact
    'contact.title': 'تواصل معنا',
    'contact.subtitle': 'هل لديك أسئلة؟ نحب أن نسمع منك. أرسل لنا رسالة وسنرد في أقرب وقت ممكن.',
    'contact.info': 'معلومات الاتصال',
    'contact.address': 'العنوان',
    'contact.addressKabul': 'كابل:',
    'contact.addressKabulText': 'مركز داوودزاي للشركات، الطابق الرابع\nكابل، أفغانستان',
    'contact.addressKhost': 'خوست:',
    'contact.addressKhostText': 'برج سلام بلازا، الطابق الثاني\nمدينة خوست، أفغانستان',
    'contact.phone': 'الهاتف',
    'contact.phone1': '۰۰۹۳۷۸۹۶۸۱۰۱۰',
    'contact.phone2': '۰۰۹۳۷۰۱۰۲۱۳۱۹',
    'contact.email': 'البريد الإلكتروني',
    'contact.email1': 'sadiq.aminzai2014@gmail.com',
    'contact.email2': 'raz.sahar2@gmail.com',
    'contact.email3': 'mohammadbilalniazi2016@gmail.com',
    'contact.hours': 'ساعات العمل',
    'contact.hoursText': 'السبت - الخميس: 8:00 صباحًا - 5:00 مساءً\nالجمعة: مغلق',
    'contact.viewMap': 'عرض على خرائط جوجل',
    'contact.form.title': 'أرسل لنا رسالة',
    'contact.form.name': 'الاسم الكامل',
    'contact.form.email': 'عنوان البريد الإلكتروني',
    'contact.form.phoneLabel': 'رقم الهاتف',
    'contact.form.subject': 'الموضوع',
    'contact.form.message': 'الرسالة',
    'contact.form.send': 'إرسال الرسالة',
    'contact.form.sending': 'جارٍ الإرسال...',
    'contact.form.namePlaceholder': 'ایان',
    'contact.form.emailPlaceholder': 'ayaan@email.com',
    'contact.form.phonePlaceholder': 'XXXXXXXX٠٧',
    'contact.form.subjectPlaceholder': 'استفسار حول النظام',
    'contact.form.messagePlaceholder': 'أود معرفة المزيد عن ميزات شفاء سكريبت...',

    // Footer
    'footer.tagline': 'نظام إدارة الرعاية الصحية',
    'footer.description': 'تمكين المهنيين الصحيين بحلول إدارة حديثة وفعالة وسهلة الاستخدام.',
    'footer.phone1': '۰۰۹۳۷۸۹۶۸۱۰۱۰',
    'footer.phone2': '۰۰۹۳۷۰۱۰۲۱۳۱۹',
    'footer.products': 'منتجات أخرى',
    'footer.product1': 'نظام معلومات المستشفى',
    'footer.product2': 'نظام إدارة المدارس',
    'footer.product3': 'نظام نقاط البيع للسوبر ماركت',
    'footer.product4': 'نظام المسلخ',
    'footer.product5': 'موقع الملف الشخصي التجاري',
    'footer.support': 'الدعم',
    'footer.contactUs': 'اتصل بنا',
    'footer.helpCenter': 'مركز المساعدة',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.terms': 'شروط الخدمة',
    'footer.copyright': '© 2026 شفاء سكريبت. جميع الحقوق محفوظة. حل إدارة الرعاية الصحية للمؤسسات.',

    // Validation
    'validation.nameMin': 'يجب أن يكون الاسم الكامل 3 أحرف على الأقل',
    'validation.emailInvalid': 'يرجى إدخال عنوان بريد إلكتروني صالح',
    'validation.phoneInvalid': 'يجب أن يكون رقم الهاتف 10 أرقام بالضبط',
    'validation.subjectLength': 'يجب أن يكون الموضوع بين 5-20 حرفًا',
    'validation.messageLength': 'يجب أن تكون الرسالة بين 12-96 حرفًا',
    'validation.fixErrors': 'يرجى إصلاح أخطاء التحقق',
    'validation.success': 'تم إرسال الرسالة بنجاح! سنعود إليك قريبًا.',
  },
};

export function LandingLanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('landing-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('landing-language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ps' || language === 'fa' || language === 'ar';

  return (
    <LandingLanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LandingLanguageContext.Provider>
  );
}

export function useLandingLanguage() {
  const context = useContext(LandingLanguageContext);
  if (!context) {
    throw new Error('useLandingLanguage must be used within LandingLanguageProvider');
  }
  return context;
}