<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Patient Report - Print</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        h1 {
            font-size: 18px;
            margin: 5px 0;
        }
        h2 {
            font-size: 16px;
            margin: 5px 0;
            color: #555;
        }
        .info {
            margin-bottom: 15px;
            display: flex;
            justify-content: space-between;
        }
        .info-section {
            width: 30%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            margin-top: 20px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            text-align: center;
            font-size: 10px;
        }
        @media print {
            body {
                margin: 0;
                padding: 10px;
            }
            button {
                display: none;
            }
        }
        .print-button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 14px;
            margin-bottom: 20px;
        }
        .print-button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <button onclick="window.print()" class="print-button">Print Report</button>
    
    <div class="header">
        <h1>Life HealthCare Center</h1>
        <p>Sayed Jamaluddin Township Road, Badkhak Square, Arzan Qemat, Kabul</p>
        <p>Contact: 0766 62 62 62</p>
        <p><b>Patient Report<b></p>
        <p>Generated on: {{ date('d-m-Y H:i:s') }}</p>
    </div>
    
    <div class="info">
        <div class="info-section">
            <p><strong>Report Type:</strong> Patient Report</p>
            <p><strong>Generated By:</strong> {{ Auth::user()->name }}</p>
        </div>
        <div class="info-section">
            <!-- Filters applied -->
            @if(!empty(session('print_filters')))
                <p><strong>Filters Applied:</strong></p>
                <ul style="list-style-type: none; padding-left: 0;">
                    @if(!empty(session('print_filters')['searchById']))
                        <li>Patient ID: {{ session('print_filters')['searchById'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchByName']))
                        <li>Patient Name: {{ session('print_filters')['searchByName'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchByCreatedAt']))
                        <li>Registration Date: {{ session('print_filters')['searchByCreatedAt'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchFromDate']) && !empty(session('print_filters')['searchToDate']))
                        <li>Date Range: {{ session('print_filters')['searchFromDate'] }} to {{ session('print_filters')['searchToDate'] }}</li>
                    @endif
                </ul>
            @endif
        </div>
        <div class="info-section">
            <p><strong>Total Records:</strong> {{ count($patients) }}</p>
            <p><strong>Report ID:</strong> PAT-{{ date('YmdHis') }}</p>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>S.No</th>
                <th>ID</th>
                <th>Name</th>
                <th>Father's Name</th>
                <th>Mobile</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Registration Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($patients as $key => $patient)
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $patient->id }}</td>
                    <td>{{ strtoupper($patient->name) }}</td>
                    <td>{{ strtoupper($patient->father_name ?? 'N/A') }}</td>
                    <td>{{ $patient->mobile ?? 'N/A' }}</td>
                    <td>{{ $patient->age ?? 'N/A' }}</td>
                    <td>{{ ucfirst($patient->gender ?? 'N/A') }}</td>
                    <td>{{ $patient->created_at->format('d-m-Y') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center;">No records found</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="footer">
        <p>© {{ date('Y') }} Life HealthCare Center. All rights reserved.</p>
        <p>This is a computer-generated document. No signature is required.</p>
    </div>

    <script>
        // Auto-print when the page loads
        window.onload = function() {
            // Give a small delay to ensure everything loads properly
            setTimeout(function() {
                // Uncomment the line below to automatically print when page loads
                // window.print();
            }, 500);
        };
    </script>
</body>
</html>