<div class="container mt-4">
    <div class="row mb-4">
        <div class="col-md-12 text-center">
            <h3>Surgery Management Report</h3>
            <p class="text-muted">Generated on: {{ date('Y-m-d H:i:s') }}</p>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th>Patient Name</th>
                    <th>Surgery</th>
                    <th>Type</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Cost</th>
                </tr>
            </thead>
            <tbody>
                @forelse($patientSurgeries as $index => $ps)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $ps->patient->name }}</td>
                    <td>{{ $ps->surgery->name }}</td>
                    <td>{{ $ps->surgery->type }}</td>
                    <td>{{ $ps->surgery_date }}</td>
                    <td>{{ ucfirst($ps->status) }}</td>
                    <td>${{ number_format($ps->cost, 2) }}</td>
                </tr>
                @empty
                <tr>
                    <td colspan="7" class="text-center">No records found.</td>
                </tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="6" class="text-end"><strong>Total Cost:</strong></td>
                    <td><strong>${{ number_format($totalCost, 2) }}</strong></td>
                </tr>
            </tfoot>
        </table>
    </div>

    <div class="row mt-5">
        <div class="col-md-4">
            <p><strong>Total Records:</strong> {{ count($patientSurgeries) }}</p>
        </div>
        <div class="col-md-4 text-center">
            <p><strong>Report Generated By:</strong> {{ Auth::user()->name }}</p>
        </div>
        <div class="col-md-4 text-end">
            <button class="btn btn-primary" onclick="window.print()">Print Report</button>
        </div>
    </div>
</div>

<style>
    @media print {
        .btn { display: none; }
        body { font-size: 12pt; }
        .container { width: 100%; max-width: 100%; }
    }
</style>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Automatically open print dialog when page loads
        window.print();
    });
</script>