<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Expiry Report - Print</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .logo {
            max-width: 80px;
            margin-bottom: 10px;
        }
        h1 {
            font-size: 18px;
            margin: 5px 0;
        }
        h2 {
            font-size: 16px;
            margin: 5px 0;
            color: #555;
        }
        .info {
            margin-bottom: 15px;
            display: flex;
            justify-content: space-between;
        }
        .info-section {
            width: 30%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            margin-top: 20px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            text-align: center;
            font-size: 10px;
        }
        .expired {
            color: #dc3545;
        }
        .about-to-expire {
            color: #ffc107;
        }
        .near-expiration {
            color: #17a2b8;
        }
        .good-condition {
            color: #28a745;
        }
        .summary {
            margin-top: 10px;
            padding: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
        }
        @media print {
            body {
                margin: 0;
                padding: 10px;
            }
            button {
                display: none;
            }
        }
        .print-button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 14px;
            margin-bottom: 20px;
        }
        .print-button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <button onclick="window.print()" class="print-button">Print Report</button>
    
    <div class="header">
        <h1>Life HealthCare Center</h1>
        <p>Sayed Jamaluddin Township Road, Badkhak Square, Arzan Qemat, Kabul</p>
        <p>Contact: 0766 62 62 62</p>
        <p><b>Stock Expiry Report<b></p>
        <p>Generated on: {{ date('d-m-Y H:i:s') }}</p>
    </div>
    
    <div class="info">
        <div class="info-section">
            <p><strong>Report Type:</strong> Stock Expiry Report</p>
            <p><strong>Generated By:</strong> {{ Auth::user()->name }}</p>
        </div>
        <div class="info-section">
            <!-- Filters applied -->
            @if(!empty(session('print_filters')))
                <p><strong>Filters Applied:</strong></p>
                <ul style="list-style-type: none; padding-left: 0;">
                    @if(!empty(session('print_filters')['searchByProduct']))
                        <li>Product ID: {{ session('print_filters')['searchByProduct'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchByBatchNo']))
                        <li>Batch No: {{ session('print_filters')['searchByBatchNo'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchByExpiryStatus']))
                        <li>Expiry Status: {{ ucfirst(str_replace('_', ' ', session('print_filters')['searchByExpiryStatus'])) }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchFromDate']) && !empty(session('print_filters')['searchToDate']))
                        <li>Date Range: {{ session('print_filters')['searchFromDate'] }} to {{ session('print_filters')['searchToDate'] }}</li>
                    @endif
                </ul>
            @endif
        </div>
        <div class="info-section">
            <p><strong>Total Records:</strong> {{ count($stocks) }}</p>
            <p><strong>Report ID:</strong> EXP-{{ date('YmdHis') }}</p>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>S.No</th>
                <th>Product</th>
                <th>Batch No</th>
                <th>Qty</th>
                <th>Mfg Date</th>
                <th>Expiry Date</th>
                <th>Days Remaining</th>
                <th>Status</th>
                <th>Unit Price</th>
            </tr>
        </thead>
        <tbody>
            @php
                $expiredCount = 0;
                $aboutToExpireCount = 0;
                $nearExpirationCount = 0;
                $goodConditionCount = 0;
            @endphp

            @forelse($stocks as $key => $stock)
                @php
                    $today = \Carbon\Carbon::today();
                    $expiryDate = \Carbon\Carbon::parse($stock->expiry_date);
                    $daysRemaining = $today->diffInDays($expiryDate, false);
                    
                    $statusClass = 'good-condition';
                    $status = 'Good Condition';
                    
                    if ($daysRemaining < 0) {
                        $statusClass = 'expired';
                        $status = 'Expired';
                        $expiredCount++;
                    } elseif ($daysRemaining <= 30) {
                        $statusClass = 'about-to-expire';
                        $status = 'About to Expire';
                        $aboutToExpireCount++;
                    } elseif ($daysRemaining <= 60) {
                        $statusClass = 'near-expiration';
                        $status = 'Near Expiration';
                        $nearExpirationCount++;
                    } else {
                        $goodConditionCount++;
                    }
                @endphp
                <tr>
                    <td>{{ $key + 1 }}</td>
                    <td>{{ $stock->product->name ?? 'N/A' }}</td>
                    <td>{{ $stock->batch_no }}</td>
                    <td>{{ $stock->quantity }}</td>
                    <td>{{ $stock->mfg_date ? date('d-m-Y', strtotime($stock->mfg_date)) : 'N/A' }}</td>
                    <td>{{ $stock->expiry_date ? date('d-m-Y', strtotime($stock->expiry_date)) : 'N/A' }}</td>
                    <td>{{ $daysRemaining > 0 ? $daysRemaining : 0 }}</td>
                    <td class="{{ $statusClass }}">{{ $status }}</td>
                    <td>{{ $stock->unit_price }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align: center;">No records found</td>
                </tr>
            @endforelse
        </tbody>
    </table>
    
    <div class="summary">
        <h4>Summary</h4>
        <table>
            <tr>
                <td><strong>Expired:</strong></td>
                <td class="expired">{{ $expiredCount }} items</td>
                <td><strong>About to Expire:</strong></td>
                <td class="about-to-expire">{{ $aboutToExpireCount }} items</td>
                <td><strong>Near Expiration:</strong></td>
                <td class="near-expiration">{{ $nearExpirationCount }} items</td>
                <td><strong>Good Condition:</strong></td>
                <td class="good-condition">{{ $goodConditionCount }} items</td>
            </tr>
        </table>
    </div>
    
    <div class="footer">
        <p>© {{ date('Y') }} Life HealthCare Center. All rights reserved.</p>
        <p>This is a computer-generated document. No signature is required.</p>
    </div>

    <script>
        // Auto-print when the page loads
        window.onload = function() {
            // Give a small delay to ensure everything loads properly
            setTimeout(function() {
                // Commented out to disable auto printing
                // window.print();
            }, 500);
        };
    </script>
</body>
</html>