<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Per-hospital barcode defaults.
 *
 *   pharmacy_default_barcode_type
 *     Which barcode type a new medicine starts on:
 *       manual        typed in by staff
 *       manufacturer  scanned from the printed packaging
 *       system        generated by ShifaaScript
 *     A pharmacy that always scans manufacturer codes should not have to change
 *     the dropdown on every product.
 *
 *   barcode_label_width_mm / barcode_label_height_mm
 *     Physical label size for the dedicated barcode printer. Defaults match the
 *     common 50x25mm pharmacy label.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('hospital_settings', function (Blueprint $table) {
            if (!Schema::hasColumn('hospital_settings', 'pharmacy_default_barcode_type')) {
                $table->string('pharmacy_default_barcode_type', 20)
                    ->default('manual')
                    ->after('pharmacy_walk_in_default_address');
            }
            if (!Schema::hasColumn('hospital_settings', 'barcode_label_width_mm')) {
                $table->unsignedSmallInteger('barcode_label_width_mm')
                    ->default(50)
                    ->after('pharmacy_default_barcode_type');
            }
            if (!Schema::hasColumn('hospital_settings', 'barcode_label_height_mm')) {
                $table->unsignedSmallInteger('barcode_label_height_mm')
                    ->default(25)
                    ->after('barcode_label_width_mm');
            }
        });
    }

    public function down(): void
    {
        Schema::table('hospital_settings', function (Blueprint $table) {
            foreach ([
                'barcode_label_height_mm',
                'barcode_label_width_mm',
                'pharmacy_default_barcode_type',
            ] as $column) {
                if (Schema::hasColumn('hospital_settings', $column)) {
                    $table->dropColumn($column);
                }
            }
        });
    }
};
