<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Barcode identification for a medicine.
 *
 *   barcode       the scannable value. Nullable -- a medicine without a barcode
 *                 stays fully searchable by name, so barcodes are never mandatory.
 *   barcode_type  manual       typed in by staff
 *                 manufacturer printed on the packaging by the manufacturer
 *                 system       generated by ShifaaScript for products that have none
 *
 * Uniqueness is per hospital: two tenants may legitimately hold the same
 * manufacturer barcode, but within one pharmacy a scan must resolve to exactly
 * one product. MySQL permits repeated NULLs in a unique index, so medicines
 * without a barcode are unaffected.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('medicines', function (Blueprint $table) {
            if (!Schema::hasColumn('medicines', 'barcode')) {
                $table->string('barcode', 64)->nullable()->after('pack_label');
            }
            if (!Schema::hasColumn('medicines', 'barcode_type')) {
                $table->string('barcode_type', 20)->nullable()->after('barcode');
            }
        });

        Schema::table('medicines', function (Blueprint $table) {
            $table->unique(['hospital_id', 'barcode'], 'medicines_hospital_barcode_unique');
        });
    }

    public function down(): void
    {
        Schema::table('medicines', function (Blueprint $table) {
            $table->dropUnique('medicines_hospital_barcode_unique');
        });

        Schema::table('medicines', function (Blueprint $table) {
            foreach (['barcode_type', 'barcode'] as $column) {
                if (Schema::hasColumn('medicines', $column)) {
                    $table->dropColumn($column);
                }
            }
        });
    }
};
