<!DOCTYPE html>
<html>
<head>
    <title>Test Type Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        h1 {
            font-size: 18px;
            margin: 0;
            padding: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 5px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            margin-top: 20px;
            font-size: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Life HealthCare Center</h1>
        <p>Sayed Jamaluddin Township Road, Badkhak Square, Arzan Qemat, Kabul</p>
        <p>Contact: 0766 62 62 62</p>
        <p><b>Laboratory Test Type Report</b></p>
    </div>
    
    <div>
        <p><strong>Date:</strong> {{ date('Y-m-d') }}</p>
        <p><strong>Time:</strong> {{ date('H:i:s') }}</p>
        <p><strong>Generated By:</strong> {{ Auth::user()->name }}</p>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>S.No</th>
                <th>ID</th>
                <th>Test Name</th>
                <th>Service Type</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($services as $key => $service)
                <tr>
                    <td style="text-align: center;">{{ $key + 1 }}</td>
                    <td>{{ $service->id }}</td>
                    <td>{{ $service->name }}</td>
                    <td>{{ $service->service_type ? $service->service_type->name : 'N/A' }}</td>
                    <td>{{ $service->created_at ? $service->created_at->format('Y-m-d') : '' }}</td>
                    <td>{{ $service->updated_at ? $service->updated_at->format('Y-m-d') : '' }}</td>
                    <td>{{ $service->is_active ? 'Active' : 'Inactive' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No records found</td>
                </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <th colspan="7" style="text-align: right;">Total Records: {{ $totalResults }}</th>
            </tr>
        </tfoot>
    </table>
    
    <div class="footer">
        <p>© {{ date('Y') }} Life HealthCare Center. All rights reserved.</p>
    </div>
</body>
</html>