<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Test Type Report - Print</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        h1 {
            font-size: 18px;
            margin: 5px 0;
        }
        h2 {
            font-size: 16px;
            margin: 5px 0;
            color: #555;
        }
        .info {
            margin-bottom: 15px;
            display: flex;
            justify-content: space-between;
        }
        .info-section {
            width: 30%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            margin-top: 20px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            text-align: center;
            font-size: 10px;
        }
        .print-button {
            display: block;
            width: 150px;
            margin: 20px auto;
            padding: 10px;
            background-color: #007bff;
            color: white;
            text-align: center;
            font-weight: bold;
            cursor: pointer;
            border: none;
            border-radius: 4px;
        }
        .print-button:hover {
            background-color: #0056b3;
        }
        @media print {
            .print-button {
                display: none;
            }
        }
    </style>
</head>
<body>
    <button onclick="window.print()" class="print-button">Print Report</button>
    
    <div class="header">
        <h1>Life HealthCare Center</h1>
        <p>Sayed Jamaluddin Township Road, Badkhak Square, Arzan Qemat, Kabul</p>
        <p>Contact: 0766 62 62 62</p>
        <p><b>Laboratory Test Type Report</b></p>
        <p>Generated on: {{ date('d-m-Y H:i:s') }}</p>
    </div>
    
    <div class="info">
        <div class="info-section">
            <p><strong>Report Type:</strong> Laboratory Test Type Report</p>
            <p><strong>Generated By:</strong> {{ Auth::user()->name }}</p>
        </div>
        <div class="info-section">
            <!-- Filters applied -->
            @if(!empty(session('print_filters')))
                <p><strong>Filters Applied:</strong></p>
                <ul style="list-style-type: none; padding-left: 0;">
                    @if(!empty(session('print_filters')['search_id']))
                        <li>ID: {{ session('print_filters')['search_id'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['search_name']))
                        <li>Name: {{ session('print_filters')['search_name'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['search_service_type_id']))
                        @php
                            $serviceTypeId = session('print_filters')['search_service_type_id'];
                            $serviceType = \App\Models\General\ServiceType::find($serviceTypeId);
                            $serviceTypeName = $serviceType ? $serviceType->name : 'N/A';
                        @endphp
                        <li>Service Type: {{ $serviceTypeName }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchFromDate']) && !empty(session('print_filters')['searchToDate']))
                        <li>Date Range: {{ session('print_filters')['searchFromDate'] }} to {{ session('print_filters')['searchToDate'] }}</li>
                    @endif
                </ul>
            @endif
        </div>
        <div class="info-section">
            <p><strong>Total Records:</strong> {{ count($query) }}</p>
            <p><strong>Report ID:</strong> LAB-TT-{{ date('YmdHis') }}</p>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>S.No</th>
                <th>ID</th>
                <th>Test Name</th>
                <th>Service Type</th>
                <th>Created At</th>
                <th>Updated At</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($query as $key => $service)
                <tr>
                    <td style="text-align: center;">{{ $key + 1 }}</td>
                    <td>{{ $service->id }}</td>
                    <td>{{ $service->name }}</td>
                    <td>{{ $service->service_type ? $service->service_type->name : 'N/A' }}</td>
                    <td>{{ $service->created_at ? $service->created_at->format('Y-m-d') : '' }}</td>
                    <td>{{ $service->updated_at ? $service->updated_at->format('Y-m-d') : '' }}</td>
                    <td>{{ $service->is_active ? 'Active' : 'Inactive' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="7" style="text-align: center;">No records found</td>
                </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <th colspan="7" style="text-align: right;">Total Records: {{ count($query) }}</th>
            </tr>
        </tfoot>
    </table>
    
    <div class="footer">
        <p>© {{ date('Y') }} Life HealthCare Center. All rights reserved.</p>
        <p>This is a computer-generated document. No signature is required.</p>
    </div>

    <script>
        // Auto-focus to the print button when the page loads
        window.onload = function() {
            document.querySelector('.print-button').focus();
        };
    </script>
</body>
</html>