<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unified Report - Print</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            font-size: 12px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
        .logo {
            max-width: 80px;
            margin-bottom: 10px;
        }
        h1 {
            font-size: 18px;
            margin: 5px 0;
        }
        h2 {
            font-size: 16px;
            margin: 5px 0;
            color: #555;
        }
        .info {
            margin-bottom: 15px;
            display: flex;
            justify-content: space-between;
        }
        .info-section {
            width: 30%;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table, th, td {
            border: 1px solid #ddd;
        }
        th, td {
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f5f5f5;
        }
        .footer {
            margin-top: 20px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            text-align: center;
            font-size: 10px;
        }
        .totals {
            margin-top: 10px;
            text-align: right;
        }
        .totals span {
            font-weight: bold;
            margin-left: 20px;
        }
        @media print {
            body {
                margin: 0;
                padding: 10px;
            }
            .print-button {
                display: none;
            }
        }
        .print-button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 14px;
            margin-bottom: 20px;
        }
        .print-button:hover {
            background-color: #45a049;
        }
        .text-right {
            text-align: right;
        }
    </style>
</head>
<body>
    <button onclick="window.print()" class="print-button">Print Report</button>
    
    <div class="header">
        <h1>Life HealthCare Center</h1>
        <p>Sayed Jamaluddin Township Road, Badkhak Square, Arzan Qemat, Kabul</p>
        <p>Contact: 0766 62 62 62</p>
        <p><b>Unified Report</b></p>
        <p>Generated on: {{ date('d-m-Y H:i:s') }}</p>
    </div>
    
    <div class="info">
        <div class="info-section">
            <p><strong>Report Type:</strong>
                @if($report_type == 'all')
                    All
                @elseif($report_type == 'fee')
                    Fee Receipts
                @elseif($report_type == 'service')
                    Service Receipts
                @elseif($report_type == 'sale')
                    Sale Invoices
                @elseif($report_type == 'return')
                    Return Invoices
                @elseif($report_type == 'purchase')
                    Purchases
                @endif
            </p>
            <p><strong>Generated By:</strong> {{ Auth::user()->name }}</p>
        </div>
        <div class="info-section">
            <!-- Filters applied -->
            @if(!empty(session('print_filters')))
                <p><strong>Filters Applied:</strong></p>
                <ul style="list-style-type: none; padding-left: 0;">
                    @if(!empty(session('print_filters')['report_type']) && session('print_filters')['report_type'] != 'all')
                        <li>Report Type: {{ ucfirst(session('print_filters')['report_type']) }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchById']))
                        <li>ID: {{ session('print_filters')['searchById'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchByPatient']))
                        <li>Patient: {{ session('print_filters')['searchByPatient'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchByDoctor']))
                        <li>Doctor: {{ session('print_filters')['searchByDoctor'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchBySupplier']))
                        <li>Supplier: {{ session('print_filters')['searchBySupplier'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchFromDate']) && !empty(session('print_filters')['searchToDate']))
                        <li>Date Range: {{ session('print_filters')['searchFromDate'] }} to {{ session('print_filters')['searchToDate'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['searchFromId']) && !empty(session('print_filters')['searchToId']))
                        <li>ID Range: {{ session('print_filters')['searchFromId'] }} to {{ session('print_filters')['searchToId'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['search_payment_status']))
                        <li>Payment Status: {{ session('print_filters')['search_payment_status'] }}</li>
                    @endif
                    @if(!empty(session('print_filters')['search_payment_method']))
                        <li>Payment Method: {{ session('print_filters')['search_payment_method'] }}</li>
                    @endif
                </ul>
            @endif
        </div>
        <div class="info-section">
            <p><strong>Total Records:</strong> {{ count($reportData) }}</p>
            <p><strong>Report ID:</strong> UNI-{{ date('YmdHis') }}</p>
        </div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Type</th>
                <th>ID/No.</th>
                <th>Date</th>
                <th>Name</th>
                <th>Doctor</th>
                <th>Service/Item</th>
                <th class="text-right">Total</th>
                <th class="text-right">Discount</th>
                <th class="text-right">Net Amount</th>
                <th class="text-right">Paid</th>
                <th class="text-right">Due</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reportData as $index => $item)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $item['type_name'] }}</td>
                <td>{{ $item['number'] }}</td>
                <td>
                    @if(is_string($item['date']))
                        {{ $item['date'] }}
                    @else
                        {{ $item['date']->format('Y-m-d') }}
                    @endif
                </td>
                <td>
                    @if(!empty($item['patient_name']))
                        {{ $item['patient_name'] }}
                    @elseif(!empty($item['supplier_name']))
                        {{ $item['supplier_name'] }}
                    @else
                        N/A
                    @endif
                </td>
                <td>{{ $item['doctor_name'] ?? 'N/A' }}</td>
                <td>{{ $item['service_name'] ?? 'N/A' }}</td>
                <td class="text-right">{{ number_format($item['total_amount'], 2) }}</td>
                <td class="text-right">{{ number_format($item['discount_amount'], 2) }}</td>
                <td class="text-right">{{ number_format($item['net_amount'], 2) }}</td>
                <td class="text-right">{{ number_format($item['paid_amount'], 2) }}</td>
                <td class="text-right">{{ number_format($item['due_amount'], 2) }}</td>
                <td>{{ $item['payment_status'] }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="13" style="text-align: center;">No data found</td>
            </tr>
            @endforelse
        </tbody>
        <tfoot>
            <tr>
                <th colspan="7" style="text-align: right;">Totals:</th>
                <th class="text-right">{{ number_format($totalAmount, 2) }}</th>
                <th class="text-right">{{ number_format($totalDiscount, 2) }}</th>
                <th class="text-right">{{ number_format($totalNetAmount, 2) }}</th>
                <th class="text-right">{{ number_format($totalPaidAmount, 2) }}</th>
                <th class="text-right">{{ number_format($totalDueAmount, 2) }}</th>
                <th></th>
            </tr>
        </tfoot>
    </table>
    
    <div class="footer">
        <p>© {{ date('Y') }} Life HealthCare Center. All rights reserved.</p>
        <p>This is a computer-generated document. No signature is required.</p>
    </div>

    <script>
        // Auto-focus to the print button when the page loads
        window.onload = function() {
            document.querySelector('.print-button').focus();
        };
    </script>
</body>
</html>